apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: pi
        image: alpine
        command: 
        - /bin/sh
        - -c
        - |
          echo $USER
      restartPolicy: Never
  backoffLimit: 1
