apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  completions: 4 # number of times to run
  parallelism: 2 # number of pods that can run in parallel
  template:
    spec:
      containers:
      - name: pi
        image: alpine
        command: ['sh', '-c', 'echo First Batch Job; sleep 10']
      restartPolicy: Never
  backoffLimit: 1
