apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-slack-notification-test
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: slack-notification-test
        image: curlimages/curl
        command:
          - "curl"
          - "-v"
          - "touch abc.txt'
          - "https://www.baeldung.com/curl-rest>>out.txt"
      restartPolicy: Never
  backoffLimit: 2
