apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: pi
        image: busybox
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done", "mkdir yamuna"]
      restartPolicy: Never
  backoffLimit: 1
