apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: pi
        image: alpine
        command: ['sh', '-c', 'echo First Batch Job; sleep 10']
      completions: 2
      restartPolicy: Never
  backoffLimit: 1
